name: Ubuntu Desktop VM
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    name: GNU/Linux System Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
 ##   - name: If failed, means ok
 ##     run: ./not-exist-file.sh it bloke build
    - name: Setting Up the Ubuntu Environment
    ##  if: ${{ failure() }}
      run: bash desktop.sh
      env:
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        CHROME_HEADLESS_CODE: ${{ secrets.CHROME_HEADLESS_CODE }}
        MACHINE_NAME: ${{ secrets.MACHINE_NAME }}
        USERNAME: ${{ secrets.USERNAME }}
        GOOGLE_REMOTE_PIN: ${{ secrets.GOOGLE_REMOTE_PIN }}
    - name: Keep Running Ubuntu System and keepAlive
    ##  if: ${{ failure() }}
      run: sleep 6h
